perf: remove eager compute calls
nicrie/xeofs pull request #110
Opened 2023-11-09 03:37 UTC by slevang

I was able to get rid of basically all the hard-coded `.compute()` calls, except for this pattern of sorting the modes by explained variance in the rotator classes:
https://github.com/nicrie/xeofs/blob/1f38a5b818a5d5fc55720e1119e6f686aef89168/xeofs/models/eof_rotator.py#L131-L139

There is a somewhat crude solution to `argsort` not being dask enabled, which is to rechunk in `mode` and do this with `apply_ufunc`:
```python
def argsort_dask(data: Data, dim: str) -> Data:
    return xr.apply_ufunc(
        np.argsort,
        data.chunk({dim: -1}),
        input_core_dims=[[dim]],
        output_core_dims=[[dim]],
        dask="parallelized",
    )

idx_sorted = argsort_dask(expvar, "mode")[::-1]
```
This should be totally fine here since `expvar` is a tiny array.

However, we still can't get around the inability to index with a `dask` array. This operation doesn't seem imperative though. @nicrie what do you think about adding a `sort` kwarg to the rotator models? If `sort=False`, we don't sort when we fit the model, but we still build the (lazy) sorted indices, so that we can easily sort things later?

2023-11-09 03:47 UTC, slevang commented on tests/models/test_eof.py
> -    new_data = mock_data_array.isel({dim[0]: slice(4, 5)})
the mock dataset only has 4 lat points so this was giving an empty slice for the `('lat', 'lon', 'time')` case

2023-11-09 03:47 UTC, slevang commented on tests/preprocessing/test_dataarray_sanitizer.py
> +@pytest.mark.parametrize(
some more tests for the modified sanitizer checks

2023-11-09 03:47 UTC, slevang commented on xeofs/data_container/data_container.py
> +            computed_data = dask.compute(computed_data)[0]
compute all simultaneously to allow dask to build a smarter task graph (only compute the SVD once)

2023-11-09 03:47 UTC, slevang commented on xeofs/models/decomposer.py
> +            min_max = xr.concat([VT.max(dims[1]), VT.min(dims[1])], dim="sign")
Had to scratch my head on this one but this seems to be a purely arithmetic way of getting the same result without any indexing ops

2023-11-09 03:47 UTC, slevang commented on xeofs/models/decomposer.py
> +        except np.linalg.LinAlgError:
`ValueError` wasn't actually raising here when I passed isolated NaNs, I think this is what we want?

2023-11-09 03:47 UTC, slevang commented on xeofs/models/gwpca.py
> +        # Hide numba imports here to greatly speed up module import time
I noticed import time was a rough ~7 seconds for `xeofs`. Did some profiling and realized it was these niche `numba` compilations. With these taken out of the main import path, we're down to ~0.7 seconds.

2023-11-09 03:47 UTC, slevang commented on xeofs/preprocessing/sanitizer.py
> +        self.is_valid_feature = self._get_valid_features(X)
I think the only thing we actually need to do in `sanitizer.fit()` is record what features should be null/notnull. Sample checking should only be part of transform to allow transform to handle new data. This way we can record this lazily as well without the compute

2023-11-09 03:47 UTC, slevang commented on xeofs/preprocessing/sanitizer.py
> +        X = X.dropna(dim=self.sample_name, how="all")
These should have the same effect as `.isel(good_indexes)` and avoids the indexing with dask array issue. We just have to make sure to first record which features were null above to do any sanity checking on the data.

2023-11-09 03:47 UTC, slevang commented on xeofs/preprocessing/sanitizer.py
> +        if not data_is_dask(X):
May as well let the SVD fail on its own when its time to compute if we're able to build everything else lazily

2023-11-09 03:47 UTC, slevang commented on xeofs/preprocessing/sanitizer.py
> +            if not X_valid_features.equals(self.is_valid_feature):
Couldn't decide whether this check should also go under the `if not dask` conditional. Any thoughts?

2023-11-09 03:47 UTC, slevang commented on xeofs/preprocessing/sanitizer.py
> +        # Don't check sample coords for unseen data
Shouldn't this be a no-op?

2023-11-09 14:17 UTC, nicrie approved these changes

2023-11-09 14:17 UTC, nicrie commented on xeofs/models/gwpca.py
> +        # Hide numba imports here to greatly speed up module import time
Nice!

2023-11-09 14:44 UTC, nicrie commented on xeofs/preprocessing/sanitizer.py
> +            if not X_valid_features.equals(self.is_valid_feature):
In its current form, it would force a computation even with Dask, right? In that case, I'd vote to apply it only to non-Dask data. We should just make it clear in the documentation (preferably [here](https://xeofs.readthedocs.io/en/latest/overview_2_features.html#handling-missing-values)) that transform automatically checks for `NaNs`, but only for non-Dask arrays.

2023-11-09 14:48 UTC, nicrie commented on xeofs/data_container/data_container.py
> +            computed_data = dask.compute(computed_data)[0]
why is the `[0]` necessary here?

2023-11-09 14:53 UTC, nicrie commented on xeofs/data_container/data_container.py
> +            computed_data = dask.compute(computed_data)[0]
I wonder is there any computational benefit of initializing `EOF(compute=True)` vs. `EOF(compute=False).fit(data, dim).compute()` ? It seems to me they should be equivalent now, but not entirely sure. In the case they are, we could also consider dropping the `compute` parameter alltogether.

2023-11-09 16:49 UTC, slevang commented on xeofs/preprocessing/sanitizer.py
> +            if not X_valid_features.equals(self.is_valid_feature):
Correct, but not on the first `fit_transform()` call, only on a second run of `transform()`. Let me implement a test to see how this actually plays out if we pass incorrect features and let this error out later. As long as that is somewhat intelligible what went wrong (or we can make it so by catching and expanding on the right error) I think your suggestion is good.

2023-11-09 16:54 UTC, slevang commented on xeofs/data_container/data_container.py
> +            computed_data = dask.compute(computed_data)[0]
Yeah that's a good point. In that case, I think it would be worth putting some work into the `model.compute()` method so that it actually computes everything necessary to save the model. As it stands it only computes the `DataContainer` objects. If we run that, then go to try and save the model later, we'll also have a bunch of intermediate outputs on the preprocessors that weren't explicitly stored and will force recomputation.

2023-11-09 16:55 UTC, slevang commented on xeofs/data_container/data_container.py
> +            computed_data = dask.compute(computed_data)[0]
> why is the `[0]` necessary here?

`dask.compute` always returns a tuple even if passed one arg (it traverses the dictionary downward here but maintains its structure). So either this or unpack the tuple on the output (`computed_data, = dask.compute(computed_data)`)

2023-11-09 16:56 UTC, slevang commented on xeofs/data_container/data_container.py
> +            computed_data = dask.compute(computed_data)[0]
I also want to experiment with the rotator sorting issue mentioned at the top before wrapping this up.

2023-11-09 19:39 UTC, nicrie commented
Sorry I had forgotten to answer to this:

> what do you think about adding a sort kwarg to the rotator models? If sort=False, we don't sort when we fit the model, but we still build the (lazy) sorted indices, so that we can easily sort things later?

That sounds reasonable to me - perhaps we can leave`sort=True` by default to not break compatibility?

2023-11-09 19:47 UTC, nicrie commented on xeofs/data_container/data_container.py
> +            computed_data = dask.compute(computed_data)[0]
> Yeah that's a good point. In that case, I think it would be worth putting some work into the `model.compute()` method so that it actually computes everything necessary to save the model. As it stands it only computes the `DataContainer` objects. If we run that, then go to try and save the model later, we'll also have a bunch of intermediate outputs on the preprocessors that weren't explicitly stored and will force recomputation.

Right..Would it be enough to iterate through the transformers and invoke `.get_serialization_attrs()`, compute and set them again through something like `set_serialization_attrs()`?

2023-11-09 19:49 UTC, slevang commented
> That sounds reasonable to me - perhaps we can leave`sort=True` by default to not break compatibility?

For sure. In the context of potentially reworking `.compute()`, I also want to look into what it would take to move this into some sort of `_post_compute()` method where we could just defer the indexing sort until after compute gets called.

2023-11-09 19:53 UTC, slevang commented on xeofs/data_container/data_container.py
> +            computed_data = dask.compute(computed_data)[0]
Yeah that's basically what I was envisioning :+1:

2023-11-09 20:06 UTC, nicrie approved these changes

2023-11-09 20:06 UTC, nicrie commented on xeofs/models/decomposer.py
> +            min_max = xr.concat([VT.max(dims[1]), VT.min(dims[1])], dim="sign")
Had to play it through line by line. Smart!

2023-11-12 12:20 UTC, slevang commented on xeofs/preprocessing/sanitizer.py
> +        X = X.dropna(dim=self.sample_name, how="all")
Was wrong about this, ultimately `dropna` calls `isel` anyways so this forces computation. I added an arg to make the nan checks optional instead, and more detail about this in the docs.

2023-11-12 12:45 UTC, slevang reviewed
Hey @nicrie I think this is ready for another look. Ended up making a bunch more changes to get full lazy execution working. I would like to do a little more manual testing of this on real datasets, and perhaps a few more small tweaks but I think it's pretty close.

2023-11-12 12:45 UTC, slevang commented on xeofs/models/_base_model.py
> +        # This feels pretty fragile with all the casing, would be
This is probably my biggest worry with this new approach is that the compute method relies on all this special casing to set the computed dask elements in the right places.

2023-11-12 12:45 UTC, slevang commented on xeofs/models/_base_model.py
> +            for k, v in dt.to_dict().items()
This traverses the whole tree and gives keys like `/preprocessor/scaler/0/mean_`, so that we are able to extract all deferred arrays in the model building process and compute simultaneously. Tested that this generally works by running on a pretty large zarr in cloud storage. Watching CPU/network activity I could see we basically stream data in from storage, compute the SVD, then do the rotation.

`dask` is known to sometimes hold on to data too long that needs to be used for future tasks, so we may get some non-optimal memory usage patterns but could probably offer additional options if those come up. E.g. it may be beneficial to pre-compute only the `mean`/`std`, to make sure dask doesn't hold onto all the data for them computing the SVD. This would require streaming the input twice.

2023-11-12 12:45 UTC, slevang commented on xeofs/models/_base_model.py
> +        # Retrieve the tree representation of each attached object, or set basic attrs
I modified the serialization structure of the `DataContainer` a bit to make this pattern cleaner. Technically breaking for deserializing any models saved by a previous version but since that's only been out a few days, probably not worth a major version.

2023-11-12 12:45 UTC, slevang commented on xeofs/models/eof_rotator.py
> +        and 100 if ``compute=False``, since we can't terminate a lazy computation
This is a little messy but if without the early stopping criteria for the rotation, 1000 iterations can take ages to run so I figured this would make the user experience a bit better.

2023-11-12 12:45 UTC, slevang commented on xeofs/models/eof_rotator.py
> +        """Re-sort the mode dimension of all data variables by variance explained."""
Moving these all out to a method we can run after compute, which allows deferring this one piece of the fit that forces execution.

2023-11-12 12:45 UTC, slevang commented on xeofs/preprocessing/scaler.py
> +            self.std_: DataVar = X.std(self.sample_dims).clip(
Was confused by a failing SVD but it was only because I had used `fillna()` for lazy execution and then was diving by zero with the std.

2023-11-13 11:11 UTC, nicrie commented
Thanks Sam for all the effort, I'll have a look at it tonight!

2023-11-14 01:55 UTC, nicrie requested changes
Really great job, Sam, thanks for the fantastic improvement! From my side, there's nothing to change (except for a few minor thingsthat I've indicated). Looking forward to trying it out :) 

btw: I'll change the target branch of the PR to the develop branch where another  fix is waiting to be released.

2023-11-14 01:55 UTC, nicrie commented on xeofs/models/eeof.py
> +                solver_kwargs=self._params["solver_kwargs"],
We probably want to incorporate the advantage of the optional sanity check here in the EEOF model. By that point, the data has already been processed by the Preprocessor, making the `NaN` check redundant.

EDIT: Not optional, but actually setting `check_nans=False`

```suggestion
                compute=self._params["compute"],
                check_nans=False,
                sample_name=self.sample_name,
                feature_name=self.feature_name,
                solver_kwargs=self._params["solver_kwargs"],
```

2023-11-14 01:55 UTC, nicrie commented on xeofs/models/eeof.py
> +            solver_kwargs=self._params["solver_kwargs"],
Same here:

```suggestion
            check_nans=self._params["check_nans"],
            sample_name=self.sample_name,
            feature_name=self.feature_name,
            solver=self._params["solver"],
            solver_kwargs=self._params["solver_kwargs"],
```

2023-11-14 01:55 UTC, nicrie commented on xeofs/models/_base_cross_model.py
>              else None
When using PCA-preprocessed MCA, checking for `NaN`s is not necessary anymore since the input data has already been `Preprocessor`-processed. So we can just setting it to `False`.


```suggestion
        self.pca1 = (
            EOF(
                n_modes=n_pca_modes,
                compute=self._params["compute"],
                check_nans=False,
            )
            if n_pca_modes
            else None
        )
        self.pca2 = (
            EOF(
                n_modes=n_pca_modes,
                compute=self._params["compute"],
                check_nans=False,
                )
            if n_pca_modes
            else None
        )
```

2023-11-14 01:55 UTC, nicrie commented on xeofs/models/opa.py
> +            solver_kwargs=self._params["solver_kwargs"],
OPA can also enjoy your new feature :) 

```suggestion
            check_nans=False,
            solver_kwargs=self._params["solver_kwargs"],
```

2023-11-14 01:55 UTC, nicrie commented on xeofs/models/eof_rotator.py
> +        and 100 if ``compute=False``, since we can't terminate a lazy computation
Yes fully agree!

2023-11-14 01:55 UTC, nicrie commented on docs/overview_2_features.rst
> +``xarray`` objects from end-to-end. By default, ``xeofs`` computes models eagerly by default, which in some
just a typo

```suggestion
If you handle large datasets that exceed memory capacity, ``xeofs`` is designed to work with ``dask``-backed
``xarray`` objects from end-to-end. By default, ``xeofs`` computes models eagerly, which in some
```

2023-11-14 01:55 UTC, nicrie reviewed
Really great job, Sam, thanks for the fantastic improvement! From my side, there's nothing to change (except for a few minor thingsthat I've indicated). Looking forward to trying it out :) 

btw: I'll change the target branch of the PR to the develop branch where another  fix is waiting to be released.

2023-11-14 03:04 UTC, slevang commented
Thanks for the review! GH wouldn't let me merge a couple of your suggestions but I added manually.

2023-11-14 11:20 UTC, nicrie commented
> Thanks for the review! GH wouldn't let me merge a couple of your suggestions but I added manually.

Ah, that was probably my bad - I guess adding suggestions (which have the  <\```suggestion ... \```> environment ) must consist of code only, without additional explanatory text? 

Just learning how to do the reviewing process, so I'm grateful for all the tricks on how to do it the right/correct/better way.

2023-11-14 11:20 UTC, nicrie approved these changes

2023-11-14 11:23 UTC, merged